### ISSUE TITLE
view helpers

### ISSUE THREAD

**Issue by lawrencec** [jedireza/hapi-react-views#16]
Is is possible to use view helpers in the react views? For instance, I'm trying to use hapi-named-routes [1] 
in the views to generate urls correctly. If not, what's the best practice for utilising useful methods (mixins?) in react views that require server context.

[1] https://github.com/poeticninja/hapi-named-routes

**Comment by jedireza** [comment]
Thanks for opening an issue. Apologies for the late reply.

We do pass the `context` object as props to the views.
https://github.com/jedireza/hapi-react-views/blob/master/index.js#L26

Have you tried this an it doesn't work?

**Comment by tjwebb** [comment]
I am passing context to reply.view but nothing is showing up in `props`

**Comment by jedireza** [comment]
@tjwebb this issue is 2 years old. If you need help please open a new issue.
