### ISSUE TITLE
Possibility to use .js extension for views

### ISSUE THREAD

**Issue by bbondy** [jedireza/hapi-react-views#22]
Wondering if it's already possible, or if not if it could be made possible to use `.js` for view extensions.
I prefer to transpile my code and babel renames the `.jsx` to `.js` in the output directory.  I run my server from the dist transpiled directory. 

I'm working around it currently with a separate gulp task that uses gulp-extname to force a .jsx extension in the output directory, but it'd be much cleaner if I could just use .js to begin with and have `server.render` find the `.js` view.

Thanks for the great project by the way!

**Comment by jedireza** [comment]
Thanks for creating an issue. There is an option you can pass `useNodeJsx`, which defaults to `true`. When `false` we'll skip using `node-jsx`. Then you could try something like:

```js
server.views({
    engines: {
        js: require('hapi-react-views') // note the key is js instead of jsx
    },
    relativeTo: __dirname,
    useNodeJsx: false,
    path: 'views'
});
```

I haven't tested this myself, but I'm guessing it could work.

**Comment by bbondy** [comment]
Thank you, I verified this works!

**Comment by abritinthebay** [comment]
for reference - this is what I'm using and it works fine:

```
server.views({
	engines: {
		js: require("hapi-react-views")
	},
	compileOptions: {
		renderMethod: "renderToString",
		useNodeJsx: false
	},
	relativeTo: __dirname,
	path: "./components"
});```
