### ISSUE TITLE
How to use babel as the jsx-transformer?

### ISSUE THREAD

**Issue by Gnimuc** [jedireza/hapi-react-views#27]
the [doc](https://github.com/jedireza/hapi-react-views#serverviewsoptions) says when using another jsx-transformer instead of `node-jsx`, one should set `useNodeJsx` to `false`. 

i want to use babel as the transformer, my configuration looks like this:
```
'visionary': {
            engines: {
                jsx: 'hapi-react-views'
            },
            compileOptions: { useNodeJsx: false },
            relativeTo: __dirname,
            path: './server/views'
        }
```
i simply added `require(babel/register)` at the top of `home.jsx`, then this error occurred.
```
Debug: internal, implementation, error 
    /Users/gnimuc/Documents/test/server/views/home.jsx:25
            <div className="commentBox">
            ^
SyntaxError: Unexpected token <
```
i guess this is not the correct way to change the jsx-transformer. 

i'm very new to nodejs, sorry for disturbing.

**Comment by jedireza** [comment]
Thanks for opening an issue. When working on #19, the goal was to turn off `node-jsx`. I believe the idea was that the `.jsx` files were already pre-processed. However what you're trying to do sounds reasonable, you may need to move the `rrequire('babel/register')` higher up. Have you tried putting that in your main server file?

**Comment by Gnimuc** [comment]
yes that was the problem. i reinstalled babel and put `require('babel/register')` in my server.js, then the error was killed. thank you so much @jedireza :+1:

**Comment by jedireza** [comment]
:boom: great to hear!!
