### ISSUE TITLE
How to add a script block to the layout ?

### ISSUE THREAD

**Issue by daslicht** [jedireza/hapi-react-views#38]
How to add a script block to the layout ?

**Comment by jedireza** [comment]
Thanks for opening an issue. I don't fully unerstand what you mean, could you elaborate?

**Comment by daslicht** [comment]
Thank you for your reply!

How would you add jQuery Plugins here:
https://github.com/jedireza/hapi-react-views/blob/master/examples/layout/views/layout.jsx#L18
Or just a inline script block

Cheers
Marc

**Comment by jedireza** [comment]
Apologies for the delay. You should be able to simply include them like any other tag. We do this in the remount example here: https://github.com/jedireza/hapi-react-views/blob/d0529ad389c7c51d2c8b5d2d62870a02b8dae9ac/examples/remount/components/html.jsx#L19

When I first started working with React I wanted to include jQuery too. I eventually learned that's not always the best way to go. I recommend checking out:

 - [Thinking in React](https://facebook.github.io/react/docs/thinking-in-react.html)
 - [Using JQuery plugins that transform the DOM in React Components?](http://stackoverflow.com/q/25436445)

**Comment by daslicht** [comment]
If I add the script tag here :
https://github.com/jedireza/hapi-react-views/blob/master/examples/layout/views/layout.jsx#L18
I just get an error

**Comment by jedireza** [comment]
Without knowing the error I'm unable to help more.

**Comment by daslicht** [comment]
never mind, i put it on ice. Probably I will post something into-depth later when I have more time.
Thank you very much !

**Comment by daslicht** [comment]
solved, i Just tried it again , and there were nor errors anymore , strange but hey GREAT
