### ISSUE TITLE
map() on array from api returns span?

### ISSUE THREAD

**Issue by mattiasewers** [jedireza/hapi-react-views#41]
I do not know why it returns a span when I map in a array...

**Comment by mattiasewers** [comment]
This seams to be an issue with spaces in jsx...

**Comment by jedireza** [comment]
Thanks for opening an issue. However, without any code it's hard to know exactly what you're running into. But in general, yes mixed text elements and regular elements in JSX will produce spans around the text elements.

> When element and non-element nodes are mixed, non-element text nodes are implicitly wrapped in Span tags. This can create sibling element nodes, on different physical lines of JSX code, which - as in the previous rule - are rendered without white space.

Source: http://www.bennadel.com/blog/2880-a-quick-look-at-rendering-white-space-using-jsx-in-reactjs.htm

**Comment by mattiasewers** [comment]
Yes, I realized that so it's fine.
