### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by robbyoconnor** [jedireza/hapi-react-views#48]

**Comment by jedireza** [comment]
It's nice that you're being active and opening issues (like: https://github.com/jedireza/drywall/issues/343). But a PR is a much more productive way to spend the energy. We have badges displayed in the readme for this.

I'm renaming the issue and adding the help-wanted flag. You're welcome and encouraged to join in and contribute. Just to be clear, I'm asking that you refrain from opening more issues about "insecure dependencies" that don't include a PR.

- - - - -

While we're at it let's review the badges we're displaying:

![badges](https://cloud.githubusercontent.com/assets/979929/13168539/95deba76-d692-11e5-9bca-9ba16f3d9355.png)

In this case the insecure dependency (`hapi@11.x` a dev-dependency) is only installed when running the test suite for this repo. In an app consumer this module the version of `hapi` they install is set by them.

Thanks again. I look forward to a PR :+1:

**Comment by robbyoconnor** [comment]
PR Pending :heart:

**Comment by robbyoconnor** [comment]
See #49

**Comment by robbyoconnor** [comment]
Now it's all green :D Pretty, pretty green

**Comment by jedireza** [comment]
Haha oh yes :green_apple: :green_book: :green_heart: :tea:
