### ISSUE TITLE
Layout feature requires JSX file extension

### ISSUE THREAD

**Issue by abritinthebay** [jedireza/hapi-react-views#56]
Just found this bug in the Layout feature.

`const layoutPath = Path.join(renderOpts.layoutPath, renderOpts.layout + '.jsx');`

That hardcodes `.jsx` which... is less than optimal. Thoughts as to a workaround? (not all projects use `.jsx` as the extension - in fact none of the ones I've worked on - closed or open - do).

Originally I had that variable as a full filename - so without the string concatenation. Thoughts?

**Comment by abritinthebay** [comment]
If you *strongly* want to have `.jsx` as the default... perhaps a `layoutExtension` option?

**Comment by jedireza** [comment]
I wonder why I had that in there. I created #57 to resolve this.

**Comment by wbprice** [comment]
I was also running into this, but #57 fixed it for me.  Thanks!
