### ISSUE TITLE
Babel transpile JSX to JS - Handling for different file extensions

### ISSUE THREAD

**Issue by danielbayerlein** [jedireza/hapi-react-views#58]
I use Babel CLI for production to compile my ES6 code to ES5. The files with the extension `.jsx` be compiled to `.js`. The server will only recognize the `.jsx` ending. How do you solve the problem?

```js
  server.views({
    engines: {
      jsx: HapiReactViews,
    },
    compileOptions: {
      doctype: '',
    },
    relativeTo: __dirname,
    path: 'views',
  });
```

**Comment by tribou** [comment]
I'm able to get my code working with:

```js
engines: {
  js: HapiReactViews,
}
```

However, you have to restart the server after every change since only `.jsx` files currently benefit from the `removeCache` option.  (I submitted #60 to hopefully resolve this.)

**Comment by jedireza** [comment]
Thanks for opening an issue @danielbayerlein. @tribou's answer should work. Please give it a shot and let us know.

**Comment by danielbayerlein** [comment]
@tribou @jedireza

Thanks for the response.
In production the server will recognize the `.js` ending - in development the `.jsx`. So I think we need a different configuration for production and development, or?

**Comment by jedireza** [comment]
I'd reach for [`confidence`](https://github.com/hapijs/confidence) in this case. `confidence` allows you to change your configuration based on a criteria (in your case `NODE_ENV`).

**Comment by danielbayerlein** [comment]
@jedireza Thank you!

**Comment by ThiagoMiranda** [comment]
@danielbayerlein Sorry to bother you in this issue but I'm experiencing the same issue here and when I add `js: HapiReactViews` in my engines configuration object I got an error:
`Unknown extension and no defaultExtension configured for view template: Default` ( my original file is name Default.jsx ).

In my view route I just put `reply.view('Default')` so do I have to write an extension? If so, how did you deal with it? Using a env argument? Thanks

**Comment by danielbayerlein** [comment]
@ThiagoMiranda Nice to hear that it works. 👍
