### ISSUE TITLE
Support removeCache option for any file extension

### ISSUE THREAD

**Issue by tribou** [jedireza/hapi-react-views#59]
Currently, `removeCache` is only supported by `.jsx` extensions as stated in the README.  However, I think I found an easy way to remove the current view and layout no matter what the extension.  Let me know if I'm misunderstanding why you're removing all `.jsx` modules from cache.

**Comment by jedireza** [comment]
Thanks for opening an issue. I'll try to check this out in more detail today. At first glance, I like it and welcome the enhancement. 🎉
