### ISSUE TITLE
Babel-register on production

### ISSUE THREAD

**Issue by ThiagoMiranda** [jedireza/hapi-react-views#67]
Hi..
Just a question: Is it safe to use babel-register ( mandatory for the JSX View ) in production? I'm currently using your package in a small app but after doing some tweaks I've stumbled into this.

Any thoughts?

Thanks

**Comment by jedireza** [comment]
Thanks for opening an issue.

[From what I've quickly read](https://www.google.com/search?q=Babel-register+on+production), it doesn't sound like it. But like most things _"your milage may vary"_.
