### ISSUE TITLE
how to pass props to layout?

### ISSUE THREAD

**Issue by kuongnp** [jedireza/hapi-react-views#70]
I using layoutPath, to set layout default in view engine.
How to pass props to layout.jsx inside view.jsx. Pass from handler.js is ok. but i want set props inside view to layout.
It is magic layout same: https://github.com/jedireza/hapi-react-views/tree/master/examples/layout
Not using tag element layout.

Thanks you.

**Comment by jedireza** [comment]
In this case, the props are shared between the layout and the view.

First we render the view with them: https://github.com/jedireza/hapi-react-views/blob/2a44c4181b81870ea2bb58d76a18469c41d1cf55/index.js#L45

Then we render the layout with them, passing the output of the view as the children of the layout: https://github.com/jedireza/hapi-react-views/blob/2a44c4181b81870ea2bb58d76a18469c41d1cf55/index.js#L47

I hope that helps.
