### ISSUE TITLE
Git Clone Link not working

### ISSUE THREAD

**Issue by DZuz14** [jedireza/hapi-react-views#73]
Just wanted to let you know.

`git clone git@github.com:jedireza/hapi-react-views.git`

In the Example section of the README gives a permissions error. I had to clone it by using the clone/download green button instead. 

Tiny issue, but thought you would like to know.

**Comment by jedireza** [comment]
I guess using ssh is my personal preference. But I've updated the example to use the https url instead.

https://help.github.com/articles/which-remote-url-should-i-use/

Thanks for opening an issue. 👍
