### ISSUE TITLE
Not issue but recommendation for updating documentation

### ISSUE THREAD

**Issue by burgerboydaddy** [jedireza/hapi-react-views#74]
Hello,
I tried to use hapi 17 with hapi-react-views and mongo-models (hapi-mongo-models) and I found the issue when I joined all together.
In general, babel (required by React) creates an error when I try to use a model.
Recommendation if using react-views and mongo-models add to app .babelrc with:
`{
  "ignore": [
    "server/api/*.js",
    "server/models/*.js"
  ]
}`
(replace my path with your).

ps. maybe this should go to hapi-mongo-models :-)

**Comment by jedireza** [comment]
Yep. This is a side effect of using Babel. In Aqua I use those modules together too and indeed, there is [a`.babelrc` file](https://github.com/jedireza/aqua/blob/ea085be912494561149e1899d68cb468e5e0d144/.babelrc#L4) where I'm ignoring the models directory.

I don't think this needs to be mentioned anywhere else besides the Babel docs. `mongo-models` uses built-in JS class and inheritance mechanics. Any module using the same patterns would be affected by Babel.
