### ISSUE TITLE
additional rendering options

### ISSUE THREAD

**Issue by travi** [jedireza/hapi-react-views#75]
would you consider supporting additional rendering approaches? 

i'd like to use emotion and support [SSR of styles](https://emotion.sh/docs/ssr), which would require processing with emotion after rendering the component. 

i'm sure you dont want to couple this plugin to emotion, so the best option might be to allow providing a function for `renderMethod` in addition to the current string options. it could expect to receive `ViewElement` and `context` as input and return the `viewOutput` string.

for example:
```js
import { renderToString } from 'react-dom/server'
import { renderStylesToString } from 'emotion-server'

const context = { name: 'Steve' };
const renderOpts = {
    runtimeOptions: {
        doctype: '<!DOCTYPE html>',
        renderMethod: (ViewElement, context) => {
          return renderStylesToString(renderToString(ViewElement(context)));
        }
    }
};

const output = await server.render('template', context, renderOpts);
```

i'd be open to sending a PR if this seems like a reasonable option to you.

**Comment by jedireza** [comment]
This is interesting. I'm interested to see what support for something like this looks like. Feel free to submit a PR.

**Comment by travi** [comment]
sorry that i havent gotten around to submitting anything for this. i could see it being valuable for some things, but my specific use case is no longer needed since [emotion 10 no longer requires special handling for SSR](https://medium.com/emotion-js/announcing-emotion-10-f1a4b17b8ccd#0c2d) so i'm going to close this out
