### ISSUE TITLE
Create an example

### ISSUE THREAD

**Issue by tcoopman** [jedireza/hapi-react-views#8]
Is it possible to create an example. If possible a somewhat complex example with multiple components and working client side injecting of React (with renderToString)?

**Comment by ro-ka** [comment]
An example would be really helpful!

I couldn't find out how to render submodules. Got my `views/index.jsx` working by looking at the tests. But now I'm trying to call render a module `<Head />` which lies in `view/head.jsx`. The error is this:

```sh
ReferenceError: Head is not defined: Head is not defined
```

How to specify it?

**Comment by ro-ka** [comment]
Ha, found it! A `var Head = require('./head.jsx');` was missing!   :)

**Comment by SOSANA** [comment]
1+ anyone working on some examples?

**Comment by jedireza** [comment]
Apologies for letting this thread go without attention. You can see `hapi-react-views` in action in [Aqua](https://github.com/jedireza/aqua/). But we do need to create some examples for this repo.

**Comment by jedireza** [comment]
:tada: Examples have been added to the README :confetti_ball: 
https://github.com/jedireza/hapi-react-views#examples
